name: multitask-network
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas>=2.0
  - pytables>=3.8
  - python>=3.10
  - pytorch-lightning>=2.0
  - rdkit=2022.09.5
  - scikit-learn=1.2.2
  - sqlalchemy>=2.0
